# Create a Pod with one Container that requests 0.5 CPU with a 1.0 CPU limit

apiVersion: v1
kind: Pod
metadata:
    name: cpu-example-pod
spec:
    containers:
    - name: cpu-example-container
      image: vish/stress
      resources:
          limits:
              cpu: "1.0"
          requests:
              cpu: "0.5"
      args:
      - -cpus
      - "2"
      # Tells the container to attempt to consume 2 CPUs
