# Create a Pod that has one container. The Container has a memory request of 100
# MiB and a memory limit of 200 MiB. Then use `stress` to test the limits.

apiVersion: v1
kind: Pod
metadata:
    name: memory-demo
    namespace: mem-example
spec:
    containers:
    - name: memory-demo-container
      image: polinux/stress
      resources:
          limits:
              memory: "1000Gi" # Exceed the memory of the Node
          requests:
              memory: "1000Gi"
      command: ["stress"]
      args: ["--vm", "1", "--vm-bytes", "150M", "--vm-hang", "1"]
